#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Project Smat: System Modular Administration Tool
File name:    smatty
Description:  Second executable for the project. This executable is forcing
              to use text-mode frontend (for teletype).

Copyright (c) since 2009 Lubos Kocman <lkocman@luboskocman.com>. All rights reserved.

"""

"""
This file is part of Smat.

Smat is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Smat is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Smat.  If not, see <http://www.gnu.org/licenses/>.

"""

import sys, os
from smat import smat
from host import host_info
from screen import *

#-------------------------------------------------------------------------------


if __name__ == "__main__":
    smat_inst = smat(smat.m_text)
    sys.exit(0)
